### ISSUE TITLE
Passing `""` to `html` cause a runtime error

### ISSUE THREAD

**Issue by slaypni** [christo-pr/dangerously-set-html-content#10]
Passing empty string `""` to `html` prop cause a runtime error:

```
Uncaught Error: html prop cant't be null
```

The sample code is:

```ts
import InnerHTML from "dangerously-set-html-content";

export default function App() {
  return (
    <div className="App">
      <InnerHTML html={""} />
    </div>
  );
}
```

Working example is:
https://codesandbox.io/s/mutable-violet-g00km1?file=/src/App.tsx

The problem did not exist in dangerously-set-html-content 1.0.8 at least.

Packages:
- dangerously-set-html-content: 1.0.13
- react: 18.2.0

**Comment by christo-pr** [comment]
hey @slaypni! 

I'm pretty sure we have this validation almost since the start of this lib, the html prop can't be null:
![image](https://user-images.githubusercontent.com/14341735/218166733-e96d3363-144c-41bd-a2c8-886fd1b8bf54.png)

So, it has to exists in order to use this lib
