### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by elr0berto** [christo-pr/dangerously-set-html-content#5]
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0 || ^16.0.0 || ^17.0.0" from dangerously-set-html-content@1.0.9

**Comment by christo-pr** [comment]
Hey @elr0berto I'll try to tackle this in the week, feel free to open a PR, should be really simple I believe :)

**Comment by Zac-Wood** [comment]
any update on this request?

**Comment by christo-pr** [comment]
This should be working now on the latest version **v1.0.10**, feel free to re-open the issue if needed
