### ISSUE TITLE
Could not find a declaration file for module 'dangerously-set-html-content' 

### ISSUE THREAD

**Issue by elr0berto** [christo-pr/dangerously-set-html-content#6]
TS7016: Could not find a declaration file for module 'dangerously-set-html-content'. '/myproj/node_modules/dangerously-set-html-content/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/dangerously-set-html-content` if it exists or add a new declaration (.d.ts) file containing `declare module 'dangerously-set-html-content'
  
  
  version:     "dangerously-set-html-content": "^1.0.10",

**Comment by christo-pr** [comment]
@elr0berto Should be fixed on the newer version: **1.0.11**

**Comment by christo-pr** [comment]
Sorry, now it should be fixed on latest version: **v1.0.12**
