### ISSUE TITLE
Script not working with Firefox

### ISSUE THREAD

**Issue by michael-scheurer** [christo-pr/dangerously-set-html-content#9]
The following script is working with Chrome, Brave etc. but not with Firefox. Any ideas how come?

`<script id="infogram_0_f9a95501-dd35-4d1f-8a2b-936b023b53b9" title="Demonstrationen im Jahr 2022" src="https://e.infogram.com/js/dist/embed.js?Nxk" type="text/javascript"/>`

**Comment by christo-pr** [comment]
Not really! we don't do any fancy thing with any JS code that is inserted, this probably is an issue from the script itself not the library.

I suggest you take a look at the JS code and see if what they are using doesn't cause any bug on those browsers, but for now, there's nothing in this lib that we could do to help you! Sorry.

**Comment by michael-scheurer** [comment]
Thanks for the super fast reply. We will take a closer look and find the cause ;)
